"""Adiciona a coluna preco à tabela de produtos

Revision ID: 70832876d915
Revises: f49c17315207
Create Date: 2024-09-24 13:53:54.812232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70832876d915'
down_revision = 'f49c17315207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.Float(), nullable=True))
        batch_op.drop_column('valor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.FLOAT(), nullable=True))
        batch_op.drop_column('preco')

    # ### end Alembic commands ###
