"""Migração inicial

Revision ID: f49c17315207
Revises: 
Create Date: 2024-09-24 09:40:55.358681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49c17315207'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=200), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    # ### end Alembic commands ###
